use_sim_time: true

amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    do_beam_skip: false
    global_frame_id: map
    lambda_short: 0.1
    laser_model_type: likelihood_field
    max_beams: 180
    max_occ_dist: 0.5
    max_range: 12.0
    min_particles: 500
    max_particles: 3000
    odom_frame_id: odom
    pf_err: 0.04
    pf_z: 0.99
    recovery_alpha_slow: 0.001
    recovery_alpha_fast: 0.1
    resample_interval: 2
    robot_model_type: differential
    save_pose_rate: 5.0
    sigma_hit: 0.2
    scan_topic: scan
    template_beam_count: 400
    update_min_a: 0.5
    update_min_d: 0.5
    wxample_thresh: -2.0
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      plugin_names: ["static_layer", "obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::StaticLayer", "nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      global_frame: map
      robot_base_frame: base_link
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.01

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 5.0
      publish_frequency: 2.0
      static_map: false
      rolling_window: true
      width: 3.0
      height: 3.0
      resolution: 0.01
